version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - db_data:/root/db
    environment:
      - FLASK_ENV=development
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  celery:
    build: ./app
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./app:/app
      - db_data:/root/db
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: